version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: ai-job-postgres
    environment:
      POSTGRES_USER: aijob
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aijob
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./deployments/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aijob"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: ai-job-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  llm-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-job-llm-server
    command: python /app/scripts/python/llm_server.py --host 0.0.0.0 --port 8000 --preload /models/qwen/Qwen3-7B --preload /models/deepseek/deepseek-coder-v3-7b
    volumes:
      - ./models:/models
      - ./models/qwen/Qwen3-7B:/models/qwen/Qwen3-7B
      - ./models/deepseek/deepseek-coder-v3-7b:/models/deepseek/deepseek-coder-v3-7b
    ports:
      - "8000:8000"
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb=128
      - TRANSFORMERS_CACHE=/models/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-job-server
    command: /app/bin/server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      llm-server:
        condition: service_started
    volumes:
      - ./config:/app/config
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aijob
      - DB_PASSWORD=password
      - DB_NAME=aijob
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LLM_SERVER_URL=http://llm-server:8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-job-worker
    command: /app/bin/worker
    depends_on:
      - server
    volumes:
      - ./config:/app/config
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aijob
      - DB_PASSWORD=password
      - DB_NAME=aijob
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LLM_SERVER_URL=http://llm-server:8000
    deploy:
      replicas: 2

  prometheus:
    image: prom/prometheus:latest
    container_name: ai-job-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
      - worker
      - llm-server

  grafana:
    image: grafana/grafana:latest
    container_name: ai-job-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: ai-job-loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: ai-job-promtail
    volumes:
      - ./:/var/log/app
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  postgres-data:
  redis-data:
  models:
  grafana-data: