version: '3.8'

services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data
    command: "agent -server -bootstrap-expect=1 -client=0.0.0.0"
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/agent/self"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  model-worker:
    build:
      context: ./model-worker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./model-worker:/app
    environment:
      - MODEL_PATH=deepseek-ai/deepseek-v3-7b
      - DEVICE=cuda
      - CONSUL_HOST=consul
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      consul:
        condition: service_healthy

  qwen-worker:
    build:
      context: ./model-worker
      dockerfile: Dockerfile.qwen
    ports:
      - "5001:5001"
    volumes:
      - ./model-worker:/app
    environment:
      - MODEL_PATH=Qwen/Qwen1.5-7B-Chat
      - DEVICE=cuda
      - CONSUL_HOST=consul
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      consul:
        condition: service_healthy

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auth
    ports:
      - "8082:8082"
    volumes:
      - ./configs:/app/configs
    environment:
      - CONSUL_HOST=consul
    networks:
      - ai-network
    depends_on:
      - consul
      - model-worker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mcp-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: mcp
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/app/configs
    environment:
      - CONSUL_HOST=consul
    networks:
      - ai-network
    depends_on:
      - consul
      - model-worker
      - auth-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: gateway
    ports:
      - "8081:8081"
    volumes:
      - ./configs:/app/configs
    environment:
      - CONSUL_HOST=consul
    networks:
      - ai-network
    depends_on:
      - consul
      - mcp-service
      - auth-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  model-cache:
  consul_data:

networks:
  ai-network:
    driver: bridge